included:
  - Sources/App
  - Sources/Lib

# Try to stay below 80
line_length:
  warning: 100
  error: 120

nesting:
  type_level: 2

type_name:
  allowed_symbols: ["_"]

disabled_rules:
  - todo
  - identifier_name
  - blanket_disable_command
